name: "🐞 Bug report"
description: Report a problem so we can fix it.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for filing a bug! Please fill in the details below."
  - type: input
    id: area
    attributes:
      label: Affected area / module
      placeholder: e.g., auth, billing, ui
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Include steps to reproduce, expected vs actual.
      placeholder: "1) … 2) … 3) …"
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: "OS, browser/node version, app version/commit"
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: ["S1 - Blocking", "S2 - Major", "S3 - Minor"]
    validations:
      required: true
