blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://example.com/docs
    about: Check if your question is answered here.
  - name: 💬 Questions / Support
    url: https://example.com/support
    about: Ask how-to questions outside of bug/feature requests.
