name: "✨ Feature request"
description: Propose a new capability or improvement.
title: "[Feature]: "
labels: ["enhancement", "needs-spec"]
assignees: []
body:
  - type: dropdown
    id: target_milestone
    attributes:
      label: Target milestone (release)
      description: Pick the release this feature should land in.
      options:
        - Pitch
        - The first milestone
        - Backlog (no target yet)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / opportunity
      description: What user problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: "Describe the UX/API, acceptance criteria, mock links"
    validations:
      required: true

  - type: checkboxes
    id: impacts
    attributes:
      label: Impacted areas
      options:
        - label: Backend
        - label: Frontend
        - label: Docs
