name: enforce-develop-into-main

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR head is not develop
        run: |
          echo "Base: ${{ github.base_ref }}"
          echo "Head: ${{ github.head_ref }}"
          if [ "${{ github.base_ref }}" = "main" ] && [ "${{ github.head_ref }}" != "develop" ]; then
            echo "❌ Only the 'develop' branch may merge into 'main'."
            exit 1
          fi
          echo "✅ Allowed."
